### ISSUE TITLE
Extend import to work for groups too.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-import#8]

**Comment by cwuensche** [comment]
@corsacca Where did the headings values come from?

For example, $contact_phone_headings has the values:
contact_phone, phone, mobile, and telephone.

**Comment by corsacca** [comment]
The plugin tries to guess the field that the csv column header corresponds to.
Those $contact_phone_headings was put there to help the plugin guess the correct field. mobile and telephone won't show up anywhere else.

**Comment by cwuensche** [comment]
@corsacca I now have a PR opened that modularizes the Import.

**Comment by corsacca** [comment]
Awesome. Thanks @cwuensche !
